title: TMUN | Toronto Model United Nations
description: TMUN is a new annual three-day high-school level Model UN conference held in downtown Toronto. # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.tmun.ca" # the base hostname & protocol for your site
# Build settings
markdown: kramdown

facebook:
  app_id: 

logo: "../css/2016_style/img/icon-large.png"

image:
  path: /css/2016_style/img/logo-small-transparent.png
  height: 1000
  width: 1000

social: 
  name: Your Facebook Page
  link: "https://www.facebook.com/"

# Google Analytics
google_analytics: UA-113696066-2

include: ['_pages']

sass:
  style: compressed

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com
  - title: twitter
    url: https://twitter.com

# Build settings
markdown: kramdown
permalink: pretty